spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/epmp
    username: root
    password: root
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB


mybatis:
  configuration:
    map-underscore-to-camel-case: true




aliyun:
  oss:
    endpoint: https://oss-cn-hangzhou.aliyuncs.com
    accessKeyId: 
    accessKeySecret: 
    bucketName: ikumzxw
#事务管理aop
logging:
  level:
    org.springframework.jdbc.support.JdbcTransactionManager: debug

# For application.yml
debug: true

